require_relative "schema_adapters/basic_adapter"
require_relative "schema_adapters/standalone_adapter"
require_relative "schema_adapters/contentless_adapter"
require_relative "schema_adapters/backed_adapter"
