name: Test
on:
  push:
    branches: ['master']
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    strategy:
      fail-fast: false
      matrix:
        include:
          ### TEST RUBY VERSIONS
          - ruby: "2.5"
          - ruby: "2.6"
          - ruby: "2.7"
          - ruby: "3.0"
          - ruby: "3.1"
          - ruby: "3.2"
          ### TEST RAILS VERSIONS
          - ruby: "2.6"
            env:
              RAILS_VERSION: "5.2"
          - ruby: "2.6"
            env:
              RAILS_VERSION: "6.0"
          - ruby: "2.6"
            env:
              RAILS_VERSION: "6.1"
          - ruby: "3.2"
            env:
              RAILS_VERSION: "7.0"
          - ruby: "3.2"
            env:
              RAILS_VERSION: "7.1"

    steps:
    - uses: actions/checkout@v3

    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
        bundler-cache: false ### not compatible with ENV style gemfile

    - name: Run test
      run: |
        bundle install
        bundle exec rake test
